### ISSUE TITLE
[Bug report] `npm init vuepress vuepress-starter` error: 'npm error `registry}` is not a valid npm option\n'

### ISSUE THREAD

**Issue by PiperLiu** [vuepress/ecosystem#311]
### Description

How to reproduce:

```bash
npm init vuepress vuepress-starter
```

> Which uses the lastest version [2.0.0-rc.12](https://www.npmjs.com/package/create-vuepress/v/2.0.0-rc.12)

Output:
```
(node:7421) ExperimentalWarning: CommonJS module /Users/piperliu/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /Users/piperliu/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

> npx
> create-vuepress vuepress-starter

? Select a language to display / 选择显示语言 简体中文
? 选择包管理器 npm
? 你想要使用哪个打包器？ vite
? 你想要创建什么类型的项目？ blog
生成 package.json...
? 设置应用名称 pliu-web-blog
? 设置应用版本号 0.0.1
? 设置应用描述 PiperLiu's bolg
? 设置协议 CC BY-SA 4.0
? 是否需要一个自动部署文档到 GitHub Pages 的工作流？ Yes
生成模板...
npm.taobao.org is no longer available, resetting it to npmmirror.com
file:///Users/piperliu/.npm/_npx/3f091d7c366309f0/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: npm config set registry} https://registry.npmmirror.com/
npm error `registry}` is not a valid npm option
npm error A complete log of this run can be found in: /Users/piperliu/.npm/_logs/2024-12-17T13_11_32_487Z-debug-0.log
    at makeError (file:///Users/piperliu/.npm/_npx/3f091d7c366309f0/node_modules/execa/lib/error.js:60:11)
    at execaSync (file:///Users/piperliu/.npm/_npx/3f091d7c366309f0/node_modules/execa/index.js:201:17)
    at execaCommandSync (file:///Users/piperliu/.npm/_npx/3f091d7c366309f0/node_modules/execa/index.js:276:9)
    at getRegistry (file:///Users/piperliu/.npm/_npx/3f091d7c366309f0/node_modules/create-vuepress/lib/utils/getRegistry.js:11:9)
    at CAC.mainAction (file:///Users/piperliu/.npm/_npx/3f091d7c366309f0/node_modules/create-vuepress/lib/action.js:78:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  shortMessage: 'Command failed with exit code 1: npm config set registry} https://registry.npmmirror.com/',
  command: 'npm config set registry} https://registry.npmmirror.com/',
  escapedCommand: 'npm config set "registry}" "https://registry.npmmirror.com/"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm error `registry}` is not a valid npm option\n' +
    'npm error A complete log of this run can be found in: /Users/piperliu/.npm/_logs/2024-12-17T13_11_32_487Z-debug-0.log',
  cwd: '/Users/piperliu/Github',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v23.3.0
```

### Reproduction

npm init vuepress vuepress-starter

### Used Package Manager

npm

### System Info

```shell
Not related to `vuepress`.
```

**Comment by PiperLiu** [comment]
I strongly believe this bug was caused by this line.
https://github.com/vuepress/ecosystem/blob/4fdde2cca2c89344d692ebad7a806a48959a3d46/tools/create-vuepress/src/utils/getRegistry.ts#L37
